### ISSUE TITLE
Error "can't send a message pfs not enabled" when using API

### ISSUE THREAD

**Issue by dshulyak** [status-im/status-console-client#113]
Sending message using API returns following error:
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"ssm_sendToContact","params":[{"name": "222"}, "plain text"],"id":1}' http://localhost:8777
```

```json
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"can't send a message: pfs not enabled"}}
```

Is it known issue? Should API be adjusted?

**Comment by dshulyak** [comment]
@adambabik do you know?

**Comment by dshulyak** [comment]
Or should i run a client with pfs turned on? Can we make it on by default?

**Comment by adambabik** [comment]
I think we should get this working without PFS enabled. We can make it enabled by default as well. I will fix this, it's a bug in the recent merge.
