### ISSUE TITLE
Error: file is encrypted or is not a database

### ISSUE THREAD

**Issue by decanus** [status-im/status-console-client#46]
Since the SQLite update, I keep getting the error "file is encrypted or is not a database" when trying to run the console client, is there some kind of setup that needs to be run beforehand? If yes this should be added to the readme so people can actually run the client.

**Comment by mandrigin** [comment]
hmm, never had this issue, @adambabik @dshulyak maybe you know?

**Comment by dshulyak** [comment]
could it be that you are using multiple different keys with the same datadir? i think this error is raised when sqlite tries to decrypt db with wrong key

**Comment by cammellos** [comment]
sqlite version differences, kdf iterations as well might be the culprit, I can have a look as well

**Comment by decanus** [comment]
@dshulyak so it seems like I don't even have a datadir, which would be located under `/tmp/status-term-client`

**Comment by dshulyak** [comment]
> @dshulyak so it seems like I don't even have a datadir, which would be located under /tmp/status-term-client

so have you tried with clean directory? sorry for dumb question :). unless you changed things mentioned by @cammellos i have no clue how to get this error

we can add a note to README that db in datadir is now encrypted. so user will have to make sure that one key = one datadir.

**Comment by oskarth** [comment]
Same issue with clean directory

**Comment by decanus** [comment]
@oskarth I generated a keypair and I am still experiencing this issue.

**Comment by oskarth** [comment]
@decanus When you generate a keypair it should persist to above tmp directory (or maybe different dir). Did you find this directory? If yes, did you remove it and regen keypair? If no, wtf maybe trace go code to see why it succeeds but doesn't persist (file dir permissions? mkdir -p /tmp/status-term-client/?)

**Comment by decanus** [comment]
Ok so I tried again it doesn’t seem to create the data dir. even though the ownership should be completely fine

**Comment by adambabik** [comment]
This is reproducible when using the same data directory but with different private keys. As we want to keep it user-friendly and don't require passing a unique data dir for each key, I suggest prefixing data dir with the public key.
