### ISSUE TITLE
-ds flag not working as expected

### ISSUE THREAD

**Issue by oskarth** [status-im/status-console-client#59]
at datasync branch commit 17f64fc09345a85f773882dbc33ad40031f53a05

> ./bin/status-term-client -keyhex=0x591a03100294b40aa5b7db609f59b174d8f04354921191947c9c5eb236a3a1d6 -ds

Writing to adamb

Expecting to see OFFER etc in

> tail -f /tmp/status-term-client/client.log

but only see

2019/05/26 17:52:43 [ChatViewController::readEventsLoops] received an event: {Interface:{baseEvent:{Contact:adamb Type:EventTypeMessage} Message:0xc00135df80}}
2019/05/26 17:52:43 [ChatViewController::readEventsLoops] selected contact adamb, msg contact adamb
2019/05/26 17:52:43 [ChatViewController::readEventsLoops] received message current clock 1558864524250 - msg clock 1558864524251
2019/05/26 17:52:43 [ChatViewController::printMessages] printing 1 messages

**Comment by oskarth** [comment]
@decanus

**Comment by decanus** [comment]
@oskarth you won't see `OFFER`s unless someone OFFERs you a message, you offering does not emit a log.
