### ISSUE TITLE
Starting client failed

### ISSUE THREAD

**Issue by decanus** [status-im/status-console-client#66]
```./bin/status-term-client -keyhex omittedlol -data-dir=../status-data -ds  2>/tmp/status-term-client.log```

```
Contact address: 0x0476f302773631d356502f557ecf7884778b8e5b8cce5cd70114a1952e17c4e35950a55bc846b39b1c48b450e429d2e0a145f98c730cdb04f39010981500bfe07b
Starting in ../status-data/0476f302773631d356502f557ecf7884778b8e5b
failed to start node: listen unix /Users/deaneigenmann/go/src/github.com/status-im/status-data/0476f302773631d356502f557ecf7884778b8e5b/geth.ipc: bind: invalid argument
```

**Comment by adambabik** [comment]
The path is too long. Not sure why go-ethereum limits it so heavily. Please try with `-no-namespace` option but remember to remove the whole dir if you use different key.

**Comment by adambabik** [comment]
Actually, it's unix thing: https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars

**Comment by decanus** [comment]
@adambabik any way we can hack that by creating a symlink?

**Comment by mandrigin** [comment]
theoretically you should be able to workaround that by not using the absolute path for a socket. or by putting the socket to `/var/run` or to `/tmp` (usual practices).

**Comment by decanus** [comment]
@mandrigin sounds simple enough

**Comment by adambabik** [comment]
@decanus or just start with `-data-dir=/tmp/test-dir`. It will fit into the 108 char bufor for sure.
