### ISSUE TITLE
Vendor Folder

### ISSUE THREAD

**Issue by decanus** [status-im/status-console-client#67]
It's usually pretty ugly practice to include folders like `vendor` in the github repository if this is something every user can easily download with assistance to the package manager. 

Unless there is a a reason for this to be include I would vouch for it to be deleted and added to the gitignore.

**Comment by adambabik** [comment]
In Go it's a normal practice. There is an official support for that with `go mod vendor`. Currently, we test on Go without Go modules support and `vendor/` makes it possible. Also, it speeds up CI pipeline as it does not need to download dependencies from the internet every time.

Source: https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away

We may get rid of this folder at some point in the future but for now I would keep it.
