### ISSUE TITLE
Copy pasting public key formatting

### ISSUE THREAD

**Issue by oskarth** [status-im/status-console-client#68]
When I want to add a contact it screw up formatting, so it shows up as

`/contacts add 0xaaaa  2 a  l o t s o f s p a c e s`

Sometimes it posts public key double as well. Pasting in other terminals works fine.

cc @adambabik

**Comment by adambabik** [comment]
https://github.com/jroimartin/gocui/issues/187

**Comment by adambabik** [comment]
Btw, it's only triggered when the terminal window size (width) is shorter than the pasted text length.

**Comment by adambabik** [comment]
Workaround proposed in #71.

**Comment by oskarth** [comment]
Ah, terminal zoom out works, thanks

**Comment by adambabik** [comment]
Closing for now because implemented workarounds are enough.
