### ISSUE TITLE
1:1 messaging not working

### ISSUE THREAD

**Issue by oskarth** [status-im/status-console-client#69]
When I add a contact and message them, they receive OFFER messages with data sync mode. I see my own messages in chat window. However, it doesn't receive any messages. This is true in both -ds mode and vanilla mode.

Public chat works, public key contact is right (since there's some communication), and mvds works in isolation.

Expected behaviour is to be able to add a contact and talk to them 1:1.

We talked about this at protocol weekly, and this (together with cursor bug) is blocking end to end testing of data sync.

cc @adambabik @mandrigin @dshulyak 

@decanus if more details

**Comment by adambabik** [comment]
I just verified and it works with `-pfs` and without. I confirmed that using Status Desktop client. Are you sure you had the latest master? It was fixed in https://github.com/status-im/status-console-client/pull/60.

I am working on the cursor bug. The temp solution is to expand terminal to full screen size.

**Comment by decanus** [comment]
@adambabik if that is the case, it may work now. I don't see any other reason why it wouldn't work. Unless there is an issue in the way I am decoding but I don't think that is the case also there is a log for that.

**Comment by oskarth** [comment]
@decanus @adambabik did we confirm it works now?

Can we run basic end to end tests w/o requiring two humans to be online sync?

**Comment by adambabik** [comment]
@oskarth yes, you can run two nodes on one machine, for example:
```
# terminal 1
$ make run ARGS="-keyhex=$NODE1_KEY -data-dir=./test-dir"

# terminal 2
$ cat node-local2.json
{
	"ListenAddr": "127.0.0.1:30403"
}
$ make run ARGS="-keyhex=$NODE2_KEY -data-dir=./test-dir -node-config=./node-local2.json"
```

Then, add Node1 as a contact to Node2 and vice versa and you will have a test of 1-1 communication on a single machine.

Alternatively, add Node as a contact to Status Desktop and start conversation.

**Comment by decanus** [comment]
@adambabik we should document this all better in the README

**Comment by decanus** [comment]
Also @oskarth and @adambabik, can we figure out a way to put that in a script?

**Comment by adambabik** [comment]
@decanus We can have some kind of e2e/smoke tests which actually use network and send messages between two nodes. What a script would be useful for?

**Comment by decanus** [comment]
@adambabik this seems to work now, closing issue.
